-- Add VARCHAR(256) limits to all name/title string fields

ALTER TABLE "Conference" ALTER COLUMN "name" TYPE VARCHAR(256) USING SUBSTRING("name" FROM 1 FOR 256);
ALTER TABLE "Hall" ALTER COLUMN "name" TYPE VARCHAR(256) USING SUBSTRING("name" FROM 1 FOR 256);
ALTER TABLE "Section" ALTER COLUMN "name" TYPE VARCHAR(256) USING SUBSTRING("name" FROM 1 FOR 256);
ALTER TABLE "Presenter" ALTER COLUMN "name" TYPE VARCHAR(256) USING SUBSTRING("name" FROM 1 FOR 256);
ALTER TABLE "Presenter" ALTER COLUMN "topic" TYPE VARCHAR(256) USING SUBSTRING("topic" FROM 1 FOR 256);
ALTER TABLE "Criterion" ALTER COLUMN "name" TYPE VARCHAR(256) USING SUBSTRING("name" FROM 1 FOR 256);
ALTER TABLE "JuryMember" ALTER COLUMN "name" TYPE VARCHAR(256) USING SUBSTRING("name" FROM 1 FOR 256);
